registration_backend
Train-lab-intern/aqa_python pull request #14
Opened 2023-09-20 09:32 UTC by SiarheiZhachek

2023-10-02 13:45 UTC, eugene-okulik requested changes, later dismissed
В целом, тесты хороши.  Но я бы во всех тестах добавил дополнительных проверок, кроме проверки статуса. Где-то сообщение, где-то что-то еще, в зависимости от того, что там возвращается.
И еще: page-object касается и тестирования API тоже. Только здесь, скорее, это будет называться endpoint-object. То есть для каждого эндпоинта можно создать класс и внутри этого класса можно описывать все действия, которые допустимы для этого эндпоинта. Ну и для всех классов эндпоинта был бы один родительский класс, в котором можно было бы собрать все действия, которые используются для каждого эндпоинта (например проверка, что статус 200). И тогда тесты бы выглядели более похоже на тесты типа: 
```
register_endpoint.create_user('asdasf@mail.com', 'Vasia', 'mypassword')
assert register_endpoint.returned_200()

2023-10-02 13:45 UTC, eugene-okulik commented on api/test_registration.py
> +        assert response.status_code == 200, f'{password}, line length is equal {len(password)}'
А почему ты здесь проверяешь статус код, а в сообщении пишешь что-то про пароль?

2023-10-02 13:45 UTC, eugene-okulik commented on api/test_registration.py
> +        assert response.status_code == 400, f'{password}, line length is equal {len(password)}'
Вот же накопипастил уже про этот пароль!

2023-10-02 13:45 UTC, eugene-okulik commented on api/test_registration.py
> +        assert response.status_code == 400
Если в требованиях прописано какая ошибка должна ожидаться, хорошо бы еще и наличие этой ошибки проверять

2024-01-15 17:04 UTC, balabkin commented on api/endpoint/registration.py
> +    def returned_201(self):
Зачем под каждый статус отдельную функцию? Проще передавать значение, которое ожидаешь аргументом

2024-01-15 17:04 UTC, balabkin commented on api/endpoint/registration.py
> +    def returned_message_invalid_email_address(self):
Тоже самое с ошибками - передавай сообщение агрументом функции, чтобы не плодить кучу одинаковых

2024-01-15 17:04 UTC, balabkin commented on conftest.py
>  from selenium.webdriver.chrome.options import Options as Options_chrome
что-то не особо здоровое ) я бы поискал какой-то другой способ использования

2024-01-15 17:04 UTC, balabkin commented on test_data.py
А зачем отдельный файл с тест датой, если есть settings?

2024-01-15 17:04 UTC, balabkin commented on api/settings.py
Вынес бы файл на уровень выше, думаю ты его не только в registration endpoint  будешь использовать в будущем

2024-02-01 14:28 UTC, merged